### ISSUE TITLE
Python implementation of BePI

### ISSUE THREAD

**Issue by b2jia** [jinhongjung/pyrwr#3]
Thank you for this great resource. Are there plans to integrate a python version of the "BePI" algorithm , which allows for fast and memory efficient RWR? RE: https://datalab.snu.ac.kr/bepi/resources/bepiSIGMOD2017.pdf

Thank you!

**Comment by jinhongjung** [comment]
Thanks for having an interest in this repository! As the lead author of the paper, I will consider your suggestion, but it could not be implemented soon since BePI requires lots of complicated numerical methods, and I am not sure there are python packages for the methods. Even if BePI is implemented in python, the performance of python could be bounded below by that of MATLAB since matrix operations in MATLAB are highly optimized. For now, consider using the MATLAB version at the link - https://datalab.snu.ac.kr/bepi/resources/BePI_matlab_v1.1.tar.gz.
